### ISSUE TITLE
Running behind Gluetun results in Exit code 4, stream does not start

### ISSUE THREAD

**Issue by sparkison** [sonroyaalmerol/m3u-stream-merger-proxy#204]
## Describe the bug

This may be simply missing from the docs, but it seems that running through a [Gluetun](https://github.com/qdm12/gluetun) service the streams fail to start.

## To Reproduce

1. Using the docker compose included below, compose the project (_replacing the VPN credentials with your own provider details and updating the m3u urls_). When attempting to play one of the streams from the playlist, the stream does not start and **Exit code 4** is shown in the logs.
2. When bypassing the Gluetun network, the proxied stream works as expected.
3. The playlist sync is working fine, as do the various endpoints, e.g: __/playlist.m3u__

## Expected behavior

Stream should work via Gluetun.

## Actual behavior

Error received when attempting to stream: **Exit code 4**

## docker-compose.yml contents

```yaml
version: "3"
services:
  # Gluetun VPN
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    network_mode: bridge
    hostname: gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${SURFSHARK_KEY}
      - WIREGUARD_ADDRESSES=${SURFSHARK_IP}
      - COUNTRY="United States"
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - UPDATER_PERIOD=24h
      #- HTTPPROXY=on # Expose port 8888 to connect
      #- HTTPPROXY_STEALTH=on
    volumes:
      - /apps/gluetun:/gluetun
    ports:
      #- 8888:8888/tcp # HTTP proxy
      - 8001:8001/tcp # Built-in HTTP control server
      - 7001:7001 # M3U Stream Merger Proxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
  # M3U Stream Merger Proxy
  m3u-proxy:
    image: sonroyaalmerol/m3u-stream-merger-proxy:latest
    container_name: m3u-proxy
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PORT=7001 # Override the default port
      - DEBUG=true
      - BUFFER_MB=2
      - SYNC_ON_BOOT=true
      - SYNC_CRON=0 0 * * *
      - M3U_URL_1=https://iptvprovider1.com/playlist.m3u
      - M3U_MAX_CONCURRENCY_1=5
      #- M3U_URL_2=https://iptvprovider2.com/playlist.m3u
      #- M3U_MAX_CONCURRENCY_2=1
      #- M3U_URL_X=
    volumes:
      # [OPTIONAL] Cache persistence: This will allow you to reuse the M3U cache across container recreates.
      - /apps/m3uproxy:/m3u-proxy/data
    restart: unless-stopped
    # Ports exposed via gluetun service
    #ports:
    #  - 7001:7001
networks: {}
```

## Container/Host Logs

```log
m3u-proxy      | 2024/12/26 23:08:57 Received request from 192.168.1.19:49199 for URL: /p/api/stream/iptvprovider1.com/livetv/KLUv_QQA1QIAooUTGXA3AsQhum4lWiWz3cQNUYCmHJ74NQIAiBWJBYNztzQlbU7M4elDBURVSzH60FAIMpyTz7XJeUttbQ4UgPPkQBQhHbr5LcjYcY5WVUcEAgCGwlAqZOIBW--fIg.m3u8
m3u-proxy      | 2024/12/26 23:08:57 [DEBUG] Stream attempt 1 out of 5
m3u-proxy      | 2024/12/26 23:08:57 Current number of connections for M3U_1: 0
m3u-proxy      | 2024/12/26 23:08:57 [DEBUG] Successfully fetched stream from https://iptvprovider1.com/livetv/channel.100.m3u8
m3u-proxy      | 2024/12/26 23:08:57 [DEBUG] Headers set for response: map[Access-Control-Allow-Headers:[Origin, X-Requested-With, Content-Type, Accept] Access-Control-Allow-Methods:[GET, OPTIONS] Access-Control-Allow-Origin:[*] Cache-Control:[max-age=5] Connection:[keep-alive] Content-Type:[application/vnd.apple.mpegurl] Date:[Thu, 26 Dec 2024 23:08:57 GMT] Etag:["676de204-ed"] Expires:[Thu, 26 Dec 2024 23:09:02 GMT] Last-Modified:[Thu, 26 Dec 2024 23:08:52 GMT] Server:[nginx]]
m3u-proxy      | 2024/12/26 23:08:57 Proxying 192.168.1.19:49199 to https://iptvprovider1.com/livetv/channel.100.m3u8
m3u-proxy      | 2024/12/26 23:08:57 Exit code 4 received from https://iptvprovider1.com/livetv/channel.100.m3u8
m3u-proxy      | 2024/12/26 23:08:57 Finished handling GET request: 192.168.1.19:49199
m3u-proxy      | 2024/12/26 23:08:57 Client disconnected: 192.168.1.19:49199
```
