### ISSUE TITLE
Docker and file errors

### ISSUE THREAD

**Issue by TgSeed** [sonroyaalmerol/m3u-stream-merger-proxy#242]
## Describe the bug

Running the same docker container as in [docker-compose.yaml](https://github.com/sonroyaalmerol/m3u-stream-merger-proxy/blob/main/docker-compose.yaml)
but facing errors like "no such file or directory."

It results in no playlist file and channels.

latest docker hub image

## To Reproduce

0. `docker pull sonroyaalmerol/m3u-stream-merger-proxy:latest`
1. Run the same docker container with the same [docker-compose.yaml](https://github.com/sonroyaalmerol/m3u-stream-merger-proxy/blob/main/docker-compose.yaml) file
2. docker compose logs

## Expected behavior

Just work

## Actual behavior

errors and no channels in playlist.m3u link.

## Container/Host Logs

```log
m3u-stream-merger-proxy  | 2025/02/15 15:10:22 [DEBUG] Parsing line: #EXTINF:-1 tvg-id="" tvg-name="Hello World 1" tvg-logo="https://example.com/p.png" group-title="Hello World",Hello World 1
m3u-stream-merger-proxy  | 2025/02/15 15:10:22 [DEBUG] Next line: http://.../.../.../...
m3u-stream-merger-proxy  | 2025/02/15 15:10:22 [DEBUG] Error creating stream cache folder: /m3u-proxy/data/streams -> mkdir /m3u-proxy/data: no space left on device
m3u-stream-merger-proxy  | 2025/02/15 15:10:22 [DEBUG] Error indexing stream: Hello World 1 (#3) -> open /m3u-proxy/data/streams/WFhYfCBHYXkgQWR1bHQgVFY=_3|1a8bf5a3c7c440dc9a723e25d2e99fa8315b38b38aa18ef01f383384: no such file or directory
m3u-stream-merger-proxy  | 2025/02/15 15:10:23 [ERROR] Error moving cache file: rename /tmp/m3u-proxy/tmp.m3u /m3u-proxy/data/cache.m3u: no such file or directory
m3u-stream-merger-proxy  | 2025/02/15 15:10:23 [INFO] Completed processing 26146 total streams
m3u-stream-merger-proxy  | 2025/02/15 15:10:23 [ERROR] Cache file reading failed: open /m3u-proxy/data/cache.m3u: no such file or directory
```

**Comment by 2-click** [comment]
The image is working fine - I pulled it a couple of hours ago.
Can you show us your compose file?
Also make sure your host system has enough space as I can see the error "no space left on device"

**Comment by TgSeed** [comment]
> The image is working fine - I pulled it a couple of hours ago. Can you show us your compose file? Also make sure your host system has enough space as I can see the error "no space left on device"

Here is the compose file:
```yaml
version: "3.8"
services:
  m3u-stream-merger-proxy:
    image: sonroyaalmerol/m3u-stream-merger-proxy:latest
    container_name: m3u-stream-merger-proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - HTTP_PROXY=http://redacted
      - HTTPS_PROXY=http:/redacted
      - NO_PROXY=localhost
      - CLEAR_ON_BOOT=true
      - SYNC_ON_BOOT=true
      - CACHE_ON_SYNC=true
      - DEBUG=false
      - SORTING_KEY=tvg-group
      - SORTING_DIRECTION=asc
      - PARSER_WORKERS=8
      - MAX_RETRIES=5
      - RETRY_WAIT=5
      - BUFFER_MB=32
      - STREAM_TIMEOUT=7
      - SYNC_CRON=0 0 * * *
      - CREDENTIALS=redacted:redacted
      - USER_AGENT=VLC
      - BASE_URL=https://m3um.mooo.com
      - M3U_URL_1=https://redacted/redacted1.m3u8
      - M3U_MAX_CONCURRENCY_1=1
      - M3U_URL_2=https://redacted/redacted2.m3u8
      - M3U_MAX_CONCURRENCY_2=1
      - M3U_URL_3=http://redacted/redacted3.m3u8
      - M3U_MAX_CONCURRENCY_3=1
    restart: unless-stopped
    tmpfs: /tmp
```

And this is the full log I get with DEBUG=false:

```
 ✔ Container m3u-stream-merger-proxy  Created                                                            0.0s 
Attaching to m3u-stream-merger-proxy
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] Starting updater...
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] CLEAR_ON_BOOT enabled. Clearing current cache.
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] Clearing memory and disk M3U cache.
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] SYNC_ON_BOOT enabled. Starting initial M3U update.
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] Background process: Updating sources...
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] Clearing memory and disk M3U cache.
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] Background process: Building merged M3U...
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] CACHE_ON_SYNC enabled. Building cache.
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] Setting up HTTP handlers...
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] Server is running on port 8080...
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] Playlist Endpoint is running (`/playlist.m3u`)
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] Stream Endpoint is running (`/p/{originalBasePath}/{streamID}.{fileExt}`)
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] Starting initial M3U cache processing...
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] Processed 100 streams so far
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] Processed 200 streams so far
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] Processed 300 streams so far
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] Processed 400 streams so far
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] Processed 500 streams so far
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] Processed 600 streams so far
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] Processed 700 streams so far
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] Processed 800 streams so far
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] Processed 900 streams so far
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] Processed 1000 streams so far
m3u-stream-merger-proxy  | 2025/02/16 13:19:49 [INFO] Processed 2000 streams so far
m3u-stream-merger-proxy  | 2025/02/16 13:20:18 [INFO] Processed 3000 streams so far
m3u-stream-merger-proxy  | 2025/02/16 13:20:18 [INFO] Processed 4000 streams so far
m3u-stream-merger-proxy  | 2025/02/16 13:20:18 [INFO] Processed 5000 streams so far
m3u-stream-merger-proxy  | 2025/02/16 13:20:18 [INFO] Processed 6000 streams so far
m3u-stream-merger-proxy  | 2025/02/16 13:20:19 [INFO] Processed 7000 streams so far
m3u-stream-merger-proxy  | 2025/02/16 13:20:19 [INFO] Processed 8000 streams so far
m3u-stream-merger-proxy  | 2025/02/16 13:20:19 [INFO] Processed 9000 streams so far
m3u-stream-merger-proxy  | 2025/02/16 13:20:19 [INFO] Processed 10000 streams so far
m3u-stream-merger-proxy  | 2025/02/16 13:20:20 [INFO] Processed 20000 streams so far
m3u-stream-merger-proxy  | 2025/02/16 13:20:23 [ERROR] Error moving cache file: rename /tmp/m3u-proxy/tmp.m3u /m3u-proxy/data/cache.m3u: no such file or directory
m3u-stream-merger-proxy  | 2025/02/16 13:20:23 [INFO] Completed processing 26146 total streams
m3u-stream-merger-proxy  | 2025/02/16 13:20:23 [ERROR] Cache file reading failed: open /m3u-proxy/data/cache.m3u: no such file or directory
```
