### ISSUE TITLE
Redis: WRONGTYPE Operation

### ISSUE THREAD

**Issue by kpirnie** [sonroyaalmerol/m3u-stream-merger-proxy#89]
with :dev tag, for every stream produces the error below
```
2024/08/20 08:34:03 Error retrieving stream for slug THE_STREAM_SLUG: error getting URL data from Redis: WRONGTYPE Operation against a key holding the wrong kind of value
2024/08/20 08:34:03 Received request from 192.168.2.20:57787 for URL: /stream/THE_STREAM
```
it happens for every stream in the the processed m3u

**Comment by sonroyaalmerol** [comment]
Can you try "resetting" your database by clearing up the data folder if you have persistence enabled? If not, try restarting Redis to clean up the data in-memory.

**Comment by kpirnie** [comment]
> Can you try "resetting" your database by clearing up the data folder if you have persistence enabled? If not, try restarting Redis to clean up the data in-memory.

Aye.  Did before posting :)
Even restarted the host machine, just in case something was hung

**Comment by kpirnie** [comment]
Something I noticed... I add: as a volume in my compose file... yet, there's nothing in it...
```volumes:
      - /home/kpirnie/pirnie-media/proxy:/data```

**Comment by kpirnie** [comment]
My bad... I'm not persisting redis apparently lol
```
services:
  sprox:
    image: sonroyaalmerol/m3u-stream-merger-proxy:dev
    container_name: kpm_sprox
    hostname: kpm_sprox
    environment:
      - PUID=1000
      - PGID=1000
      - REDIS_ADDR=192.168.2.200:6379
      - TZ=America/New_York
      - SYNC_ON_BOOT=true
      - SYNC_CRON=0 0 * * *
      - M3U_URL_1=file:///playlists/kp-shows.m3u
      - M3U_MAX_CONCURRENCY_1=2
      - PARSER_WORKERS=8
      - BUFFER_MB=512
    volumes:
      - /home/kpirnie/pirnie-media/playlists/M3U:/playlists
      - /home/kpirnie/pirnie-media/proxy:/data
    ports:
      - 8000:8080
    tmpfs: /tmp
    restart: unless-stopped
```
